---
title: "R Notebook"
output: html_notebook
---


```{r}
{
  library(tidyverse)
  library(Biostrings)
}

extract_string <- function(x, n, i, delimiter){
  
    do.call(c, lapply(x, function(X)
        paste(unlist(strsplit(X, delimiter))[(n+1):(i)], 
              collapse = delimiter)))
}
```



```{r}

# db_STRSeq <- read_delim("data/sequence.fasta", 
#                         delim = "\t", 
#                         escape_double = FALSE, 
#                         col_names = FALSE, 
#                         trim_ws = TRUE)

# dl_STRSeq <- read.table(text = system(paste0("esearch -db nuccore -query '380127 [GPRJ]' | efetch -format fasta"),
#                                       intern = TRUE),
#                         sep = "\t")
# write_tsv(dl_STRSeq, file = "data/sequence.fasta",
#           col_names = FALSE)

db_STRSeq <- readDNAStringSet("data/sequence.fasta")
db_STRSeq_working <- data.frame(id = names(db_STRSeq), 
                        sequences = as.character(db_STRSeq)) %>%
  mutate(Locus = extract_string(id, 4, 5, 
                                delimiter = " "),
         GenBankID = extract_string(id, 0, 1, 
                                    delimiter =" "),
         Kit = extract_string(id, 
                              (nchar(id) - nchar(gsub(" ", "", id))) - 1, 
                              (nchar(id) - nchar(gsub(" ", "", id))), 
                              delimiter = " "))

```







